# Global timezone labels.
# Format can be LABEL,OFFSET or {"OFFSET", "LABEL"}.
# The firmware keeps one whole-hour offset list and applies matching labels.
BAK,-12
PPG,-11
HNL,-10
ANC,-9
LA,-8
DEN,-7
CHI,-6
NYC,-5
SCL,-4
RIO,-3
FEN,-2
PDL,-1
LON,0
PAR,+1
CAI,+2
MOW,+3
DXB,+4
KHI,+5
DAC,+6
BKK,+7
SHA,+8
TOK,+9
SYD,+10
NOU,+11
AKL,+12
TBU,+13
CXI,+14
